version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: web
    container_name: web
    hostname: web
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - ./mysqld:/run/mysqld
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  db:
    image: mysql
    container_name: mysql
    hostname: mysql
    ports:
      - "3307:3307"
    restart: always
    environment:
      MYSQL_HOST: "localhost"
      MYSQL_PORT: "3307"
      MYSQL_DATABASE: "mysql_django"
      MYSQL_USER: "dev"
      MYSQL_PASSWORD: "1234"
      MYSQL_ALLOW_EMPTY_PASSWORD: "ture"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysqld:/var/run/mysqld


